name: CI

on:
  push:
    

jobs:
  verification:
    name : verification
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci
    - name: lint
      run: npm run lint

  cypress-test:
    name: cypress test
    needs: verification
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm run cy:run
    - name: Upload Screenshots reports
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: cypress-screenshots
        path: cypress/screenshots
    - name: Upload video reports
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: videos
        path: cypress/videos
    - name: Merge reports
      if: always()
      run: npm run report:merge
    - name: change to HTML
      if: always()
      run: npm run report:html
    - name: Upload HTML report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: mochawesome-report
        path: mochawesome-report